import type { LocalItem } from './types';

export const localArticles: LocalItem[] = [
  {
    id: 'article-1',
    title: 'How to structure a construction knowledge feed that gets read',
    summary: 'Editorial guidance on post formats, tagging, and ranked discovery.',
    field: 'Project Management',
    tags: ['feed', 'ranking', 'knowledge'],
    location: 'Kenya',
    contentTypes: ['text', 'images', 'documents'],
    author: 'Editorial Desk',
    metrics: '1.8k reads',
    createdAt: '2026-04-01T09:00:00Z',
    kind: 'Article',
    verified: true,
  },
  {
    id: 'article-2',
    title: 'Site-photo documentation for cleaner claims workflows',
    summary: 'Patterns for image-first evidence packs and timestamped commentary.',
    field: 'Engineering',
    tags: ['site photos', 'claims', 'documentation'],
    location: 'Nairobi',
    contentTypes: ['images', 'documents', 'video'],
    author: 'Field Ops',
    metrics: '930 reads',
    createdAt: '2026-03-29T08:00:00Z',
    kind: 'Guide',
    verified: true,
  },
  {
    id: 'article-3',
    title: 'Foundation QA checklist: what inspectors flag first',
    summary: 'A practical checklist for footing depth, bar spacing, cover blocks, and concrete test-cube records before pour signoff.',
    field: 'Engineering',
    tags: ['foundation', 'quality', 'inspection'],
    location: 'Kisumu',
    contentTypes: ['text', 'documents'],
    author: 'Civil QA Unit',
    metrics: '1.2k reads',
    createdAt: '2026-04-04T07:30:00Z',
    kind: 'Checklist',
    verified: true,
  },
  {
    id: 'article-4',
    title: 'Rebar congestion fixes for transfer slabs',
    summary: 'Field-tested detailing patterns to reduce clashes between couplers, sleeves, and MEP openings in dense reinforcement zones.',
    field: 'Engineering',
    tags: ['rebar', 'structural', 'detailing'],
    location: 'Nairobi',
    contentTypes: ['text', 'images', 'documents'],
    author: 'Structural Forum',
    metrics: '2.1k reads',
    createdAt: '2026-04-03T10:05:00Z',
    kind: 'Article',
    verified: true,
  },
  {
    id: 'article-5',
    title: 'Cost control playbook for volatile steel pricing',
    summary: 'How QS teams lock rates, model alternates, and protect schedule when supplier lead times and prices fluctuate.',
    field: 'Project Management',
    tags: ['cost-control', 'procurement', 'steel'],
    location: 'Mombasa',
    contentTypes: ['text', 'documents'],
    author: 'Commercial Office',
    metrics: '1.5k reads',
    createdAt: '2026-04-02T13:20:00Z',
    kind: 'Guide',
    verified: true,
  },
  {
    id: 'article-6',
    title: 'Waterproofing failures at wet areas: 8 repeat mistakes',
    summary: 'An audit of handover snags across bathrooms, balconies, and podium decks with prevention steps for each defect type.',
    field: 'Architecture',
    tags: ['waterproofing', 'handover', 'defects'],
    location: 'Nakuru',
    contentTypes: ['text', 'images'],
    author: 'Envelope Team',
    metrics: '1.9k reads',
    createdAt: '2026-04-01T09:50:00Z',
    kind: 'Article',
    verified: false,
  },
  {
    id: 'article-7',
    title: 'Site logistics zones that cut truck idle time by 35%',
    summary: 'Layout strategies for entry control, crane pick zones, and vertical transport booking to keep deliveries flowing.',
    field: 'Project Management',
    tags: ['logistics', 'planning', 'productivity'],
    location: 'Kiambu',
    contentTypes: ['text', 'images', 'video'],
    author: 'Field Operations Lab',
    metrics: '1.1k reads',
    createdAt: '2026-03-31T15:10:00Z',
    kind: 'Case Study',
    verified: true,
  },
  {
    id: 'article-8',
    title: 'Curtain wall QA: tolerance checks before glazing',
    summary: 'A pre-glazing verification workflow for plumbness, anchor torque logs, and sealant compatibility records.',
    field: 'Engineering',
    tags: ['facade', 'quality', 'glazing'],
    location: 'Nairobi',
    contentTypes: ['text', 'documents'],
    author: 'Facade Review Desk',
    metrics: '980 reads',
    createdAt: '2026-03-30T08:40:00Z',
    kind: 'Technical Note',
    verified: true,
  },
  {
    id: 'article-9',
    title: 'MEP coordination in tight ceiling voids',
    summary: 'Practical routing priorities for ducts, trays, and sprinkler mains with BIM snapshots and rework avoidance metrics.',
    field: 'Engineering',
    tags: ['mep', 'coordination', 'bim'],
    location: 'Eldoret',
    contentTypes: ['text', 'images', 'documents'],
    author: 'MEP Integration Team',
    metrics: '1.6k reads',
    createdAt: '2026-03-29T11:15:00Z',
    kind: 'Article',
    verified: true,
  },
  {
    id: 'article-10',
    title: 'Safety leadership brief: improving toolbox talk outcomes',
    summary: 'How shorter, role-specific toolbox talks improved near-miss reporting and reduced repeat safety violations.',
    field: 'Project Management',
    tags: ['safety', 'leadership', 'training'],
    location: 'Thika',
    contentTypes: ['text', 'audio'],
    author: 'HSE Practice Group',
    metrics: '760 reads',
    createdAt: '2026-03-28T06:55:00Z',
    kind: 'Brief',
    verified: false,
  },
  {
    id: 'article-11',
    title: 'Procurement sequencing for long-lead MEP equipment',
    summary: 'A sequencing guide for approvals, submittals, and FAT milestones to avoid commissioning delays.',
    field: 'Project Management',
    tags: ['procurement', 'mep', 'schedule'],
    location: 'Naivasha',
    contentTypes: ['text', 'documents'],
    author: 'Planning Office',
    metrics: '1.3k reads',
    createdAt: '2026-03-27T14:35:00Z',
    kind: 'Guide',
    verified: true,
  },
  {
    id: 'article-12',
    title: 'Snag closeout system for faster practical completion',
    summary: 'A digital closeout model using zone ownership, photo evidence, and SLA timers that cut pending snags by half.',
    field: 'Engineering',
    tags: ['closeout', 'quality', 'handover'],
    location: 'Nairobi',
    contentTypes: ['text', 'images', 'documents'],
    author: 'Commissioning Circle',
    metrics: '2.4k reads',
    createdAt: '2026-03-26T09:05:00Z',
    kind: 'Article',
    verified: true,
  },
  {
    id: 'article-13',
    title: 'Low-carbon concrete options for commercial towers',
    summary: 'Comparing SCM blends, embodied carbon impacts, and curing constraints for high-rise structural elements.',
    field: 'Engineering',
    tags: ['sustainability', 'concrete', 'materials'],
    location: 'Mombasa',
    contentTypes: ['text', 'documents'],
    author: 'Materials Lab',
    metrics: '1.7k reads',
    createdAt: '2026-03-25T10:00:00Z',
    kind: 'Research Note',
    verified: true,
  },
  {
    id: 'article-14',
    title: 'Digital daily reports that clients actually review',
    summary: 'A reporting format that combines field photos, blockers, and 48-hour lookahead to improve decision turnaround.',
    field: 'Project Management',
    tags: ['reporting', 'clients', 'workflow'],
    location: 'Nakuru',
    contentTypes: ['text', 'images'],
    author: 'PMO Insights',
    metrics: '1.0k reads',
    createdAt: '2026-03-24T16:20:00Z',
    kind: 'Article',
    verified: false,
  },
];

export const discussionThreads: LocalItem[] = [
  {
    id: 'thread-1',
    title: 'How do you manage approval delays without stalling site works?',
    summary: 'Replies discuss escalation trees, weekly cadence, and client dashboards.',
    field: 'Project Management',
    tags: ['approvals', 'workflow', 'risk'],
    location: 'Nakuru',
    contentTypes: ['text'],
    author: 'A. Kariuki',
    metrics: '18 replies',
    createdAt: '2026-04-03T07:20:00Z',
    kind: 'Discussion',
    replies: '18',
    votes: '+42',
  },
  {
    id: 'thread-2',
    title: 'Mentions and follow-ups for consultant accountability',
    summary: 'Thread showing replies, mentions, and vote patterns for better closure.',
    field: 'Engineering',
    tags: ['mentions', 'comments', 'follow-up'],
    location: 'Nairobi',
    contentTypes: ['text', 'video'],
    author: 'S. Mwangi',
    metrics: '24 replies',
    createdAt: '2026-04-02T08:45:00Z',
    kind: 'Discussion',
    replies: '24',
    votes: '+61',
  },
];

export const qaItems: LocalItem[] = [
  {
    id: 'qa-1',
    title: 'How do you price a design-build bid for mixed-use towers?',
    summary: 'Top answers cover risk premiums, site constraints, and escalation buffers.',
    field: 'Project Management',
    tags: ['bidding', 'pricing', 'commercial'],
    location: 'Nairobi',
    contentTypes: ['text', 'documents'],
    author: 'Q&A Board',
    metrics: 'Accepted answer',
    createdAt: '2026-04-03T09:10:00Z',
    kind: 'Q&A',
    replies: '9',
    votes: '+31',
  },
  {
    id: 'qa-2',
    title: 'How should site photos be organized for progress claims?',
    summary: 'Best responses recommend location tags and weekly evidence bundles.',
    field: 'Engineering',
    tags: ['site photos', 'claims', 'documentation'],
    location: 'Mombasa',
    contentTypes: ['images', 'documents'],
    author: 'Q&A Board',
    metrics: 'Top answer',
    createdAt: '2026-04-02T11:30:00Z',
    kind: 'Q&A',
    replies: '14',
    votes: '+27',
  },
];

export const marketplaceItems: LocalItem[] = [
  {
    id: 'market-1',
    title: 'Client bidding: 3-storey office fit-out',
    summary: 'Submit bids with scope notes, certifications, and timeline commitments.',
    field: 'Project Management',
    tags: ['bid', 'marketplace', 'office'],
    location: 'Nairobi',
    contentTypes: ['text', 'documents'],
    author: 'BuildSmart Client',
    metrics: 'KES 8.6M budget',
    createdAt: '2026-04-01T13:00:00Z',
    kind: 'Marketplace',
    budget: 'KES 8.6M',
    status: 'Open for bids',
  },
  {
    id: 'market-2',
    title: 'Residential electrical package for coastal villas',
    summary: 'Professionals can submit scoped offers and proof of past delivery.',
    field: 'Engineering',
    tags: ['bid', 'electrical', 'coastal'],
    location: 'Kilifi',
    contentTypes: ['text', 'images'],
    author: 'Client Desk',
    metrics: '12 bids',
    createdAt: '2026-03-31T12:30:00Z',
    kind: 'Marketplace',
    budget: 'KES 1.4M',
    status: 'Open for bids',
  },
];

export const eventAnnouncements: LocalItem[] = [
  {
    id: 'event-1',
    title: 'Webinar: Construction reputation and digital trust',
    summary: 'Session on profiles, certifications, follows, and moderation.',
    field: 'Project Management',
    tags: ['webinar', 'reputation', 'profiles'],
    location: 'Online',
    contentTypes: ['video', 'text'],
    author: 'ICDBO Live',
    metrics: 'Starts in 2 days',
    createdAt: '2026-04-02T18:00:00Z',
    kind: 'Event',
  },
  {
    id: 'event-2',
    title: 'Regional meetup: Coastal builders and suppliers',
    summary: 'Networking and breakouts for project leaders in the coastal region.',
    field: 'Engineering',
    tags: ['regional', 'networking', 'meetup'],
    location: 'Mombasa',
    contentTypes: ['text', 'images'],
    author: 'Community Hosts',
    metrics: '120 RSVPs',
    createdAt: '2026-04-01T16:30:00Z',
    kind: 'Event',
  },
];

export const pollItems: LocalItem[] = [
  {
    id: 'poll-1',
    title: 'What content should we prioritize this month?',
    summary: 'Pick between technical guides, site photo stories, and opportunity alerts.',
    field: 'Engineering',
    tags: ['poll', 'survey', 'content'],
    location: 'All regions',
    contentTypes: ['text'],
    author: 'Community',
    metrics: '642 votes',
    createdAt: '2026-04-03T14:00:00Z',
    kind: 'Poll',
  },
  {
    id: 'poll-2',
    title: 'Follow topics first or people first during onboarding?',
    summary: 'Used to tune recommendations and first-week engagement flow.',
    field: 'Project Management',
    tags: ['poll', 'onboarding', 'recommendations'],
    location: 'All regions',
    contentTypes: ['text'],
    author: 'Product',
    metrics: '311 votes',
    createdAt: '2026-04-02T09:30:00Z',
    kind: 'Poll',
  },
];

export const trendingTopics = [
  '#sitephotos',
  '#tendering',
  '#bim',
  '#coastalprojects',
  '#qsworkflow',
  '#smartbuildings',
];

export const notifications = [
  { id: 'n1', title: '3 likes on your last post', body: 'Your post is gaining traction in Project Management.' },
  { id: 'n2', title: '2 new replies', body: 'A discussion thread you follow has fresh comments.' },
  { id: 'n3', title: '1 new follow', body: 'A verified contractor followed your profile.' },
];

export const creatorAnalytics = [
  { label: 'Views', value: '12.4k' },
  { label: 'Engagement', value: '8.7%' },
  { label: 'Bookmarks', value: '421' },
];

export const moderationQueue = [
  { id: 'm1', title: 'Spam filter review', body: '2 posts were auto-flagged for repeated outbound links.' },
  { id: 'm2', title: 'Report review', body: '1 post is awaiting moderation from the admin queue.' },
];

export const contentTypes = ['text', 'images', 'video', 'documents', 'site photos'];
