import type { CommunityPost } from '@/lib/community';

/**
 * Comprehensive mock community data with diverse content types
 * - 30% Videos (16 posts)
 * - 30% Images (16 posts)
 * - 15% Text (8 posts)
 * - 15% Documents (8 posts)
 * - 10% Audio (5 posts)
 * Total: 53 posts
 */

const generateTimestamp = (daysAgo: number, hoursAgo: number = 0): string => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  date.setHours(date.getHours() - hoursAgo);
  return date.toISOString();
};

const authors = [
  { name: 'Alex Chen', role: 'Structural Engineer', verified: true },
  { name: 'Maria Santos', role: 'Architect', verified: true },
  { name: 'James K. Kipchoge', role: 'Project Manager', verified: true },
  { name: 'Priya Sharma', role: 'QS/Quantity Surveyor', verified: false },
  { name: 'David O\'Brien', role: 'Construction Manager', verified: true },
  { name: 'Fatima Al-Rashid', role: 'MEP Engineer', verified: true },
  { name: 'Carlos Rodriguez', role: 'Site Supervisor', verified: false },
  { name: 'Sophie Martin', role: 'Architect', verified: false },
  { name: 'Raj Patel', role: 'BIM Coordinator', verified: true },
  { name: 'Lisa Thompson', role: 'Safety Officer', verified: true },
  { name: 'Marco Rossi', role: 'Contractor', verified: false },
  { name: 'Amara Okafor', role: 'Environmental Officer', verified: false },
];

const getRandomAuthor = () => authors[Math.floor(Math.random() * authors.length)];
const getRandomEngagement = () => ({
  likes: Math.floor(Math.random() * 500) + 10,
  comments: Math.floor(Math.random() * 50) + 2,
});

export const mockCommunityData: CommunityPost[] = [
  // ============================================
  // VIDEOS (30%) - 16 posts
  // ============================================
  {
    id: 'mock-video-001',
    type: 'Site Video',
    title: 'Live pour: 450 cubic meters concrete in 8 hours',
    summary: 'Real-time documentation of foundation slab concrete pouring. High-speed cinematography shows placement, vibration, and finishing techniques.',
    author: 'Alex Chen',
    field: 'Engineering',
    interests: ['concrete', 'construction', 'video'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.w3schools.com/html/mov_bbb.mp4', mediaType: 'video' as const, fileName: 'concrete_pour.mp4' }],
    createdAt: generateTimestamp(0, 3),
  },
  {
    id: 'mock-video-002',
    type: 'Construction Update',
    title: 'Structural steel erection timelapse - 2 days, 120 connections',
    summary: 'Time-lapse of steel frame assembly showing precision bolting and welding quality checks.',
    author: 'David O\'Brien',
    field: 'Engineering',
    interests: ['steel', 'structural', 'timelapse'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://media.w3.org/2010/05/sintel/trailer.mp4', mediaType: 'video' as const, fileName: 'steel_erection.mp4' }],
    createdAt: generateTimestamp(1, 0),
  },
  {
    id: 'mock-video-003',
    type: 'Safety Training',
    title: 'Heights safety certification - Harness fitting and anchor points',
    summary: 'Comprehensive training video on working at heights. Proper equipment inspection and emergency protocols.',
    author: 'Lisa Thompson',
    field: 'Safety',
    interests: ['safety', 'training', 'certification'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.w3schools.com/html/mov_bbb.mp4', mediaType: 'video' as const, fileName: 'safety_training.mp4' }],
    createdAt: generateTimestamp(2, 5),
  },
  {
    id: 'mock-video-004',
    type: 'Drone Survey',
    title: 'Aerial site overview - 3D progress documentation',
    summary: 'Weekly drone survey showing overall site progress. Multiple altitudes and angles for stakeholder reports.',
    author: 'Raj Patel',
    field: 'Engineering',
    interests: ['drone', 'survey', '3d-documentation'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://media.w3.org/2010/05/sintel/trailer.mp4', mediaType: 'video' as const, fileName: 'drone_survey.mp4' }],
    createdAt: generateTimestamp(2, 8),
  },
  {
    id: 'mock-video-005',
    type: 'Technical Walkthrough',
    title: 'MEP rough-in coordination - Electrical, plumbing, HVAC integration',
    summary: 'Detailed walkthrough of coordinated rough-in phase showing clash avoidance and system integration.',
    author: 'Fatima Al-Rashid',
    field: 'Engineering',
    interests: ['mep', 'coordination', 'technical'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.w3schools.com/html/mov_bbb.mp4', mediaType: 'video' as const, fileName: 'mep_roughin.mp4' }],
    createdAt: generateTimestamp(3, 2),
  },
  {
    id: 'mock-video-006',
    type: 'Installation Guide',
    title: 'Curtain wall installation sequence - Precision glazing placement',
    summary: 'Step-by-step video of curtain wall installation showing mullion positioning and glass panel placement techniques.',
    author: 'Sophie Martin',
    field: 'Architecture',
    interests: ['facade', 'installation', 'details'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [{ url: 'https://media.w3.org/2010/05/sintel/trailer.mp4', mediaType: 'video' as const, fileName: 'curtain_wall.mp4' }],
    createdAt: generateTimestamp(3, 6),
  },
  {
    id: 'mock-video-007',
    type: 'Testing Documentation',
    title: 'Fire-rated door assembly testing - 2-hour burn test',
    summary: 'Full documentation of fire-rating compliance test with thermal imaging and temperature monitoring.',
    author: 'Maria Santos',
    field: 'Architecture',
    interests: ['testing', 'compliance', 'safety'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.w3schools.com/html/mov_bbb.mp4', mediaType: 'video' as const, fileName: 'fire_test.mp4' }],
    createdAt: generateTimestamp(4, 1),
  },
  {
    id: 'mock-video-008',
    type: 'Commissioning',
    title: 'HVAC system startup sequence - Full flow balance verification',
    summary: 'Commissioning walkthrough showing air handler startup, damper operation, and ductwork pressurization.',
    author: 'Fatima Al-Rashid',
    field: 'Engineering',
    interests: ['hvac', 'commissioning', 'systems'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://media.w3.org/2010/05/sintel/trailer.mp4', mediaType: 'video' as const, fileName: 'hvac_startup.mp4' }],
    createdAt: generateTimestamp(4, 10),
  },
  {
    id: 'mock-video-009',
    type: 'Progress Update',
    title: 'Interior fit-out sprint - Week 4 timelapse',
    summary: '7-day compressed view of partitioning, fixture installation, and finishes application.',
    author: 'James K. Kipchoge',
    field: 'Management',
    interests: ['fit-out', 'progress', 'timelapse'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.w3schools.com/html/mov_bbb.mp4', mediaType: 'video' as const, fileName: 'fitout_timelapse.mp4' }],
    createdAt: generateTimestamp(5, 3),
  },
  {
    id: 'mock-video-010',
    type: 'Educational Content',
    title: 'BIM clash detection workflow - Resolving MEP intersections',
    summary: 'Tutorial on using BIM software to identify and resolve clashes before construction begins.',
    author: 'Raj Patel',
    field: 'Engineering',
    interests: ['bim', 'coordination', 'technology'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://media.w3.org/2010/05/sintel/trailer.mp4', mediaType: 'video' as const, fileName: 'bim_tutorial.mp4' }],
    createdAt: generateTimestamp(5, 7),
  },
  {
    id: 'mock-video-011',
    type: 'Equipment Demo',
    title: 'New laser scanner - 3D point cloud capture in real-time',
    summary: 'Technology demonstration of latest 3D scanning equipment for as-built documentation.',
    author: 'Alex Chen',
    field: 'Engineering',
    interests: ['technology', 'equipment', 'innovation'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.w3schools.com/html/mov_bbb.mp4', mediaType: 'video' as const, fileName: 'laser_scanner.mp4' }],
    createdAt: generateTimestamp(6, 2),
  },
  {
    id: 'mock-video-012',
    type: 'Quality Check',
    title: 'Rebar placement verification - Automated dimensional checking',
    summary: 'QA documentation showing reinforcement placement accuracy within tolerance.',
    author: 'Priya Sharma',
    field: 'QS',
    interests: ['quality', 'verification', 'structural'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [{ url: 'https://media.w3.org/2010/05/sintel/trailer.mp4', mediaType: 'video' as const, fileName: 'rebar_check.mp4' }],
    createdAt: generateTimestamp(6, 5),
  },
  {
    id: 'mock-video-013',
    type: 'Logistics',
    title: 'Material delivery optimization - Reduced wait times 40%',
    summary: 'Case study of improved site logistics planning reducing congestion and delivery delays.',
    author: 'James K. Kipchoge',
    field: 'Management',
    interests: ['logistics', 'optimization', 'efficiency'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.w3schools.com/html/mov_bbb.mp4', mediaType: 'video' as const, fileName: 'logistics.mp4' }],
    createdAt: generateTimestamp(7, 1),
  },
  {
    id: 'mock-video-014',
    type: 'Sustainability',
    title: 'Renewable energy system installation - Solar panel deployment',
    summary: 'Documentation of 580 kW solar array installation across building roof surfaces.',
    author: 'Amara Okafor',
    field: 'Sustainability',
    interests: ['renewable', 'sustainability', 'energy'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [{ url: 'https://media.w3.org/2010/05/sintel/trailer.mp4', mediaType: 'video' as const, fileName: 'solar_install.mp4' }],
    createdAt: generateTimestamp(7, 4),
  },
  {
    id: 'mock-video-015',
    type: 'Site Tour',
    title: 'Architectural walkthrough - 360° perspective of completed zones',
    summary: 'Comprehensive tour with architect commentary on design intent, material selections, and spatial flow.',
    author: 'Maria Santos',
    field: 'Architecture',
    interests: ['architecture', 'design', 'tour'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.w3schools.com/html/mov_bbb.mp4', mediaType: 'video' as const, fileName: 'arch_tour.mp4' }],
    createdAt: generateTimestamp(8, 0),
  },
  {
    id: 'mock-video-016',
    type: 'Before & After',
    title: 'Transformation: Demolition to new frame in 72 hours',
    summary: 'Time-compressed 3-day project phase showing entire demolition and structural setup sequence.',
    author: 'David O\'Brien',
    field: 'Engineering',
    interests: ['progress', 'transformation', 'timelapse'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://media.w3.org/2010/05/sintel/trailer.mp4', mediaType: 'video' as const, fileName: 'before_after.mp4' }],
    createdAt: generateTimestamp(8, 8),
  },

  // ============================================
  // IMAGES (30%) - 16 posts
  // ============================================
  {
    id: 'mock-image-001',
    type: 'Site Update',
    title: 'Foundation complete - Ready for structural steel',
    summary: 'Foundation phase milestone achieved. All concrete cured and inspected. Quality verification signed off.',
    author: 'Alex Chen',
    field: 'Engineering',
    interests: ['foundation', 'milestone', 'structure'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [
      { url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80', mediaType: 'image', fileName: 'foundation.jpg' },
    ],
    createdAt: generateTimestamp(0, 6),
  },
  {
    id: 'mock-image-002',
    type: 'Team Spotlight',
    title: 'Team of the month: Concrete crew achieves record pour rate',
    summary: 'Recognition to 12-person team for 450 m³ in single shift with zero defects.',
    author: 'James K. Kipchoge',
    field: 'Management',
    interests: ['team', 'recognition', 'excellence'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [
      { url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80', mediaType: 'image', fileName: 'team_photo.jpg' },
    ],
    createdAt: generateTimestamp(1, 1),
  },
  {
    id: 'mock-image-003',
    type: 'Material Delivery',
    title: 'Ceramic tiles & fixtures arrival - 4,200 sq meters inspected',
    summary: 'Complete bathroom and kitchen tile shipment arrived. All units verified for defects. Climate-controlled storage.',
    author: 'Priya Sharma',
    field: 'QS',
    interests: ['materials', 'delivery', 'logistics'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [
      { url: 'https://images.unsplash.com/photo-1576574587620-9f4ee4b54b2d?w=800&q=80', mediaType: 'image', fileName: 'tiles.jpg' },
    ],
    createdAt: generateTimestamp(1, 2),
  },
  {
    id: 'mock-image-004',
    type: 'Design Feature',
    title: 'Interior finishes approved - 8 paint colors, 12 flooring options',
    summary: 'Architect selection finalized. All materials sourced. Sample verification complete.',
    author: 'Maria Santos',
    field: 'Architecture',
    interests: ['design', 'finishes', 'materials'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [
      { url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80', mediaType: 'image', fileName: 'interiors.jpg' },
    ],
    createdAt: generateTimestamp(2, 3),
  },
  {
    id: 'mock-image-005',
    type: 'Landscape Design',
    title: 'Native plant selection for hardscape zones - Sustainability focus',
    summary: '450 trees, 2,200 shrubs, 8,900 flowering plants selected for native species program.',
    author: 'Amara Okafor',
    field: 'Sustainability',
    interests: ['landscaping', 'sustainability', 'design'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [
      { url: 'https://images.unsplash.com/photo-1497206365907-3d71b2f17570?w=800&q=80', mediaType: 'image', fileName: 'landscape.jpg' },
    ],
    createdAt: generateTimestamp(2, 9),
  },
  {
    id: 'mock-image-006',
    type: 'Safety Achievement',
    title: '14-day safety record - Zero incidents milestone',
    summary: 'Full site completed 2 weeks without any safety incidents or near-misses.',
    author: 'Lisa Thompson',
    field: 'Safety',
    interests: ['safety', 'milestone', 'achievement'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [
      { url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80', mediaType: 'image', fileName: 'safety.jpg' },
    ],
    createdAt: generateTimestamp(3, 4),
  },
  {
    id: 'mock-image-007',
    type: 'Electrical Systems',
    title: 'Electrical panel installation complete - 2,400m conduit, 890 boxes',
    summary: 'Rough-in phase 40% complete. All boxes positioned. Coordination with MEP on schedule.',
    author: 'Fatima Al-Rashid',
    field: 'Engineering',
    interests: ['electrical', 'mep', 'systems'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [
      { url: 'https://images.unsplash.com/photo-1574482620811-1aa16ffe3c82?w=800&q=80', mediaType: 'image', fileName: 'electrical.jpg' },
    ],
    createdAt: generateTimestamp(3, 7),
  },
  {
    id: 'mock-image-008',
    type: 'Quality Assurance',
    title: 'Precast panels QA - 240 units, 100% pass dimensional verification',
    summary: 'Compression tests exceed architect specs. Finish quality premium standard.',
    author: 'Priya Sharma',
    field: 'QS',
    interests: ['quality', 'testing', 'precast'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [
      { url: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800&q=80', mediaType: 'image', fileName: 'qa.jpg' },
    ],
    createdAt: generateTimestamp(4, 2),
  },
  {
    id: 'mock-image-009',
    type: 'LEED Certification',
    title: 'Project tracking toward LEED Platinum - 87 points earned',
    summary: 'Path to 95+ points. Water efficiency and energy systems exceeding targets.',
    author: 'Amara Okafor',
    field: 'Sustainability',
    interests: ['sustainability', 'leed', 'certification'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [
      { url: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80', mediaType: 'image', fileName: 'leed.jpg' },
    ],
    createdAt: generateTimestamp(4, 6),
  },
  {
    id: 'mock-image-010',
    type: 'Facade System',
    title: 'Curtain wall 85% complete - 480 glass panels installed and sealed',
    summary: '1,440 aluminum mullions. Air tightness testing scheduled. Quality on target.',
    author: 'Sophie Martin',
    field: 'Architecture',
    interests: ['facade', 'glass', 'curtainwall'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [
      { url: 'https://images.unsplash.com/photo-1486152873792-f510acf2f3a0?w=800&q=80', mediaType: 'image', fileName: 'facade.jpg' },
    ],
    createdAt: generateTimestamp(5, 1),
  },
  {
    id: 'mock-image-011',
    type: 'Roofing Installation',
    title: 'Roof membrane application - 4,500 sq meters, TPO fully mechanically attached',
    summary: 'Thermal imaging verified complete coverage. Waterproofing certified.',
    author: 'Carlos Rodriguez',
    field: 'Supervision',
    interests: ['roofing', 'waterproofing', 'installation'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [
      { url: 'https://images.unsplash.com/photo-1581092162392-8c6c592e33c1?w=800&q=80', mediaType: 'image', fileName: 'roofing.jpg' },
    ],
    createdAt: generateTimestamp(5, 5),
  },
  {
    id: 'mock-image-012',
    type: 'Fire Safety Systems',
    title: 'Fire suppression system tested - Response time <60 seconds across 12 floors',
    summary: 'Water pressure 8 bar maintained. Certification obtained. All tests passed.',
    author: 'Lisa Thompson',
    field: 'Safety',
    interests: ['fire-safety', 'systems', 'testing'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [
      { url: 'https://images.unsplash.com/photo-1581092335281-7e9b4d9bb2f6?w=800&q=80', mediaType: 'image', fileName: 'fire_safety.jpg' },
    ],
    createdAt: generateTimestamp(6, 0),
  },
  {
    id: 'mock-image-013',
    type: 'Accessibility Audit',
    title: 'ADA compliance verification - 100% compliant public areas',
    summary: 'Third-party verification. All ramps, elevators, restrooms certified accessible.',
    author: 'James K. Kipchoge',
    field: 'Management',
    interests: ['accessibility', 'compliance', 'ada'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [
      { url: 'https://images.unsplash.com/photo-1578375076-b5f8e4a6e5f0?w=800&q=80', mediaType: 'image', fileName: 'accessibility.jpg' },
    ],
    createdAt: generateTimestamp(6, 3),
  },
  {
    id: 'mock-image-014',
    type: 'Parking Infrastructure',
    title: 'Underground parking - 450 spaces, 3-level structure excavation complete',
    summary: 'Diaphragm walls installed and waterproofed. Ready for structural concrete.',
    author: 'David O\'Brien',
    field: 'Engineering',
    interests: ['parking', 'infrastructure', 'excavation'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [
      { url: 'https://images.unsplash.com/photo-1580857940606-cac922e12908?w=800&q=80', mediaType: 'image', fileName: 'parking.jpg' },
    ],
    createdAt: generateTimestamp(7, 2),
  },
  {
    id: 'mock-image-015',
    type: 'Waste Management',
    title: 'Recycling milestone - 76% material diversion from landfill',
    summary: '450 tons recycled material. 340 tons concrete, steel, wood. Cost savings: $23,400.',
    author: 'Amara Okafor',
    field: 'Sustainability',
    interests: ['sustainability', 'waste', 'recycling'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [
      { url: 'https://images.unsplash.com/photo-1559027615-cd25e57e7e0e?w=800&q=80', mediaType: 'image', fileName: 'recycling.jpg' },
    ],
    createdAt: generateTimestamp(7, 6),
  },
  {
    id: 'mock-image-016',
    type: 'Energy Systems',
    title: 'Solar panels installed - 580 kW capacity, 45% energy cost reduction',
    summary: '8,400 LED fixtures throughout building. System projected live next month.',
    author: 'Fatima Al-Rashid',
    field: 'Engineering',
    interests: ['energy', 'solar', 'sustainability'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [
      { url: 'https://images.unsplash.com/photo-1509391366360-2e938103d514?w=800&q=80', mediaType: 'image', fileName: 'solar.jpg' },
    ],
    createdAt: generateTimestamp(8, 1),
  },

  // ============================================
  // TEXT POSTS (15%) - 8 posts
  // ============================================
  {
    id: 'mock-text-001',
    type: 'Article',
    title: 'Best practices: Choosing reinforced concrete mixes for coastal construction',
    summary: 'Technical deep dive into chloride resistance strategies, admixture selection, and QA sampling for marine-facing structures. Essential reading for projects in high-salinity environments.',
    author: 'Alex Chen',
    field: 'Engineering',
    interests: ['concrete', 'design', 'materials'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [],
    createdAt: generateTimestamp(1, 10),
  },
  {
    id: 'mock-text-002',
    type: 'Discussion',
    title: 'How do you balance speed vs. quality on tight schedules?',
    summary: 'Open discussion on project management strategies. Share your approaches to maintaining quality standards when schedule pressure increases.',
    author: 'James K. Kipchoge',
    field: 'Management',
    interests: ['management', 'discussion', 'best-practices'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [],
    createdAt: generateTimestamp(2, 11),
  },
  {
    id: 'mock-text-003',
    type: 'Insight',
    title: 'Why structural engineers love Revit (and sometimes hate it)',
    summary: 'A candid take on using BIM software for structural modeling. Discussing workflow optimization and common pitfalls.',
    author: 'Raj Patel',
    field: 'Engineering',
    interests: ['bim', 'software', 'workflow'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [],
    createdAt: generateTimestamp(3, 8),
  },
  {
    id: 'mock-text-004',
    type: 'Question',
    title: 'What fire-rated door solutions would you recommend for healthcare facilities?',
    summary: 'Seeking recommendations for FRL ratings, acoustic performance, and accessibility compliance.',
    author: 'Sophie Martin',
    field: 'Architecture',
    interests: ['fire-safety', 'healthcare', 'doors'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [],
    createdAt: generateTimestamp(4, 4),
  },
  {
    id: 'mock-text-005',
    type: 'Expert Opinion',
    title: 'The future of construction: AI-powered site monitoring changing the game',
    summary: 'Industry analysis on how machine learning and computer vision are transforming on-site quality control and safety.',
    author: 'Raj Patel',
    field: 'Engineering',
    interests: ['technology', 'innovation', 'ai'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [],
    createdAt: generateTimestamp(5, 9),
  },
  {
    id: 'mock-text-006',
    type: 'News',
    title: 'New sustainability standard ISO 21959:2024 now available - What you need to know',
    summary: 'Summary of updated environmental standards for construction projects and how to prepare for compliance.',
    author: 'Amara Okafor',
    field: 'Sustainability',
    interests: ['standards', 'compliance', 'sustainability'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [],
    createdAt: generateTimestamp(6, 7),
  },
  {
    id: 'mock-text-007',
    type: 'Tip',
    title: 'Quick wins: 5 ways to reduce concrete formwork costs 15-20%',
    summary: 'Practical strategies for optimizing formwork systems, reusability, and labor efficiency.',
    author: 'Priya Sharma',
    field: 'QS',
    interests: ['cost-control', 'efficiency', 'formwork'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [],
    createdAt: generateTimestamp(7, 0),
  },
  {
    id: 'mock-text-008',
    type: 'Reflection',
    title: 'Lessons learned: Managing stakeholder expectations on a 400M project',
    summary: 'Personal reflection on communication strategies that worked and some that didn\'t. Valuable insights for large-scale projects.',
    author: 'David O\'Brien',
    field: 'Engineering',
    interests: ['management', 'leadership', 'lessons'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [],
    createdAt: generateTimestamp(8, 5),
  },

  // ============================================
  // DOCUMENTS (15%) - 8 posts
  // ============================================
  {
    id: 'mock-doc-001',
    type: 'Report',
    title: 'Q1 2026 Financial Report - Under budget 3.2%, Schedule ahead 2.8%',
    summary: 'Comprehensive financial and schedule analysis. Material costs optimized. Labor efficiency improved 15%.',
    author: 'James K. Kipchoge',
    field: 'Management',
    interests: ['budget', 'schedule', 'reporting'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', mediaType: 'document', fileName: 'Q1_Report.pdf' }],
    createdAt: generateTimestamp(0, 12),
  },
  {
    id: 'mock-doc-002',
    type: 'Method Statement',
    title: 'Temporary works method statement - Retaining wall excavation sequence',
    summary: 'Detailed method statement with phased excavation, tieback installation, and emergency controls.',
    author: 'Alex Chen',
    field: 'Engineering',
    interests: ['method-statement', 'temporary-works', 'safety'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.africau.edu/images/default/sample.pdf', mediaType: 'document', fileName: 'Method_Statement.pdf' }],
    createdAt: generateTimestamp(1, 14),
  },
  {
    id: 'mock-doc-003',
    type: 'Specification',
    title: 'Structural steel specification - Grade 50, connection details, QA requirements',
    summary: 'Complete fabrication and assembly specifications for all major structural steel elements.',
    author: 'Alex Chen',
    field: 'Engineering',
    interests: ['specification', 'steel', 'standards'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.orimi.com/pdf-test.pdf', mediaType: 'document', fileName: 'Steel_Spec.pdf' }],
    createdAt: generateTimestamp(2, 1),
  },
  {
    id: 'mock-doc-004',
    type: 'Site Bulletin',
    title: 'Weekly quality bulletin - Rebar cover nonconformities and corrective action',
    summary: 'QA bulletin with inspection photos, root causes, and corrected bar spacing checklist for all crews.',
    author: 'Priya Sharma',
    field: 'QS',
    interests: ['quality', 'rebar', 'defects'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [{ url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', mediaType: 'document', fileName: 'Weekly_QA_Bulletin.pdf' }],
    createdAt: generateTimestamp(3, 2),
  },
  {
    id: 'mock-doc-005',
    type: 'Safety Plan',
    title: 'Site-wide safety and health plan - Rev 3 (Updated March 2026)',
    summary: 'Comprehensive H&S documentation covering hazard register, emergency procedures, and incident response.',
    author: 'Lisa Thompson',
    field: 'Safety',
    interests: ['safety', 'hse', 'planning'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.africau.edu/images/default/sample.pdf', mediaType: 'document', fileName: 'Safety_Plan_Rev3.pdf' }],
    createdAt: generateTimestamp(4, 3),
  },
  {
    id: 'mock-doc-006',
    type: 'Design Guide',
    title: 'Waterproofing failures and how to catch them before handover',
    summary: 'Lessons learned from 5 projects including substrate prep, membrane detailing, and flood test documentation.',
    author: 'Maria Santos',
    field: 'Architecture',
    interests: ['waterproofing', 'design', 'handover'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.orimi.com/pdf-test.pdf', mediaType: 'document', fileName: 'Waterproofing_Guide.pdf' }],
    createdAt: generateTimestamp(5, 2),
  },
  {
    id: 'mock-doc-007',
    type: 'Compliance Certificate',
    title: 'Municipal inspection report - Foundation phase PASSED',
    summary: 'Official municipal certification for foundation phase. Zero defects. Approved to proceed.',
    author: 'James K. Kipchoge',
    field: 'Management',
    interests: ['compliance', 'inspection', 'certification'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', mediaType: 'document', fileName: 'Inspection_Certificate.pdf' }],
    createdAt: generateTimestamp(6, 1),
  },
  {
    id: 'mock-doc-008',
    type: 'Technical Manual',
    title: 'BIM execution plan - Information requirements and deliverables',
    summary: 'Complete BIM documentation strategy for all project phases and stakeholder coordination.',
    author: 'Raj Patel',
    field: 'Engineering',
    interests: ['bim', 'planning', 'documentation'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.africau.edu/images/default/sample.pdf', mediaType: 'document', fileName: 'BIM_Execution_Plan.pdf' }],
    createdAt: generateTimestamp(7, 3),
  },

  // ============================================
  // AUDIO (10%) - 5 posts
  // ============================================
  {
    id: 'mock-audio-001',
    type: 'Podcast',
    title: 'Construction Leadership Podcast - Managing night shift fatigue on high-rise projects',
    summary: 'Expert discussion on shift handovers, incident prevention habits, and scheduling improvements for worker safety and productivity.',
    author: 'Lisa Thompson',
    field: 'Safety',
    interests: ['podcast', 'leadership', 'safety'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', mediaType: 'audio', fileName: 'night_shift_safety.mp3' }],
    createdAt: generateTimestamp(0, 14),
  },
  {
    id: 'mock-audio-002',
    type: 'Toolbox Talk',
    title: 'Audio toolbox talk - Confined space entry controls and atmospheric testing',
    summary: 'Recorded safety briefing for permit checks, atmospheric testing procedures, and standby rescue protocols.',
    author: 'Lisa Thompson',
    field: 'Safety',
    interests: ['audio', 'hse', 'toolbox-talk'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3', mediaType: 'audio', fileName: 'confined_space_talk.mp3' }],
    createdAt: generateTimestamp(1, 11),
  },
  {
    id: 'mock-audio-003',
    type: 'Podcast',
    title: 'Materials Matters - Procurement strategy when steel prices fluctuate wildly',
    summary: 'Commercial and engineering teams explain framework agreements, alternates, and schedule risk buffers.',
    author: 'Priya Sharma',
    field: 'QS',
    interests: ['podcast', 'procurement', 'strategy'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [{ url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3', mediaType: 'audio', fileName: 'steel_procurement.mp3' }],
    createdAt: generateTimestamp(3, 10),
  },
  {
    id: 'mock-audio-004',
    type: 'Training',
    title: 'Safety training audio - Proper PPE donning and equipment inspection checklist',
    summary: 'Comprehensive audio guide for new site personnel covering all mandatory safety equipment procedures.',
    author: 'Lisa Thompson',
    field: 'Safety',
    interests: ['audio', 'training', 'pce'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3', mediaType: 'audio', fileName: 'ppe_training.mp3' }],
    createdAt: generateTimestamp(5, 12),
  },
  {
    id: 'mock-audio-005',
    type: 'Interview',
    title: 'Project director interview - Career path and lessons learned over 20 years',
    summary: 'In-depth interview sharing insights on project management evolution, team development, and industry trends.',
    author: 'David O\'Brien',
    field: 'Engineering',
    interests: ['interview', 'experience', 'career'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [{ url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3', mediaType: 'audio', fileName: 'director_interview.mp3' }],
    createdAt: generateTimestamp(7, 8),
  },

  // ============================================
  // ADDITIONAL CONSTRUCTION ARTICLES
  // ============================================
  {
    id: 'mock-article-009',
    type: 'Article',
    title: 'Concrete pour hold points every site team should enforce',
    summary: 'Defines mandatory hold points from pre-pour checks to cube logging, preventing common slab defects and costly repairs.',
    author: 'Alex Chen',
    field: 'Engineering',
    interests: ['article', 'concrete', 'quality'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [
      { url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', mediaType: 'document', fileName: 'concrete_hold_points.pdf' },
      { url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80', mediaType: 'image', fileName: 'concrete_pour_site.jpg' },
    ],
    createdAt: generateTimestamp(1, 4),
  },
  {
    id: 'mock-article-010',
    type: 'Article',
    title: 'Managing RFIs without slowing site production',
    summary: 'A framework for RFI triage and response SLAs that keeps crews productive while technical clarifications are resolved.',
    author: 'James K. Kipchoge',
    field: 'Project Management',
    interests: ['article', 'rfi', 'coordination'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [
      { url: 'https://www.orimi.com/pdf-test.pdf', mediaType: 'document', fileName: 'rfi_workflow_guide.pdf' },
    ],
    createdAt: generateTimestamp(2, 3),
  },
  {
    id: 'mock-article-011',
    type: 'Technical Brief',
    title: 'Facade sealant compatibility checks before final closeout',
    summary: 'A technical brief on substrate prep, primer selection, and bond testing to avoid facade leakage claims.',
    author: 'Sophie Martin',
    field: 'Architecture',
    interests: ['facade', 'sealants', 'article'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [
      { url: 'https://www.africau.edu/images/default/sample.pdf', mediaType: 'document', fileName: 'facade_sealant_brief.pdf' },
      { url: 'https://images.unsplash.com/photo-1486152873792-f510acf2f3a0?w=800&q=80', mediaType: 'image', fileName: 'facade_detail.jpg' },
    ],
    createdAt: generateTimestamp(2, 9),
  },
  {
    id: 'mock-article-012',
    type: 'Article',
    title: 'Sequencing MEP first-fix in congested shafts',
    summary: 'Trade-by-trade sequencing guidance to reduce rework and maintain inspection access throughout first-fix execution.',
    author: 'Fatima Al-Rashid',
    field: 'Engineering',
    interests: ['mep', 'sequencing', 'article'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [
      { url: 'https://www.orimi.com/pdf-test.pdf', mediaType: 'document', fileName: 'mep_shaft_sequencing.pdf' },
      { url: 'https://images.unsplash.com/photo-1574482620811-1aa16ffe3c82?w=800&q=80', mediaType: 'image', fileName: 'mep_coordination.jpg' },
    ],
    createdAt: generateTimestamp(3, 5),
  },
  {
    id: 'mock-article-013',
    type: 'Article',
    title: 'Interpreting slump test trends across multiple pours',
    summary: 'How to interpret variability in slump and tie corrective actions to batching, transit time, and admixture dosage.',
    author: 'Marco Rossi',
    field: 'Engineering',
    interests: ['concrete', 'testing', 'article'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [
      { url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', mediaType: 'document', fileName: 'slump_test_analysis.pdf' },
    ],
    createdAt: generateTimestamp(4, 6),
  },
  {
    id: 'mock-article-014',
    type: 'Guide',
    title: 'Procurement buffers for long-lead façade and elevator packages',
    summary: 'A planning guide for submittals, factory approvals, and delivery windows to protect critical path milestones.',
    author: 'Priya Sharma',
    field: 'QS',
    interests: ['procurement', 'planning', 'article'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [
      { url: 'https://www.africau.edu/images/default/sample.pdf', mediaType: 'document', fileName: 'long_lead_buffers.pdf' },
    ],
    createdAt: generateTimestamp(5, 1),
  },
  {
    id: 'mock-article-015',
    type: 'Article',
    title: 'Weekly site photos that improve payment certification speed',
    summary: 'Photo evidence standards and location tagging patterns that help consultants validate completed quantities faster.',
    author: 'Carlos Rodriguez',
    field: 'Engineering',
    interests: ['site-photos', 'claims', 'article'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [
      { url: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800&q=80', mediaType: 'image', fileName: 'site_photo_pack.jpg' },
    ],
    createdAt: generateTimestamp(5, 8),
  },
  {
    id: 'mock-article-016',
    type: 'Article',
    title: 'Risk review cadence for design-build high-rise projects',
    summary: 'How weekly risk registers, owner assignments, and lookahead meetings reduce surprises during peak construction periods.',
    author: 'David O\'Brien',
    field: 'Project Management',
    interests: ['risk', 'management', 'article'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [],
    createdAt: generateTimestamp(6, 4),
  },
  {
    id: 'mock-article-017',
    type: 'Research Note',
    title: 'Low-carbon concrete blends for tropical climates',
    summary: 'Comparison of SCM blend options balancing embodied carbon reduction with early strength and durability requirements.',
    author: 'Amara Okafor',
    field: 'Sustainability',
    interests: ['sustainability', 'concrete', 'article'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: false,
    media: [
      { url: 'https://www.orimi.com/pdf-test.pdf', mediaType: 'document', fileName: 'low_carbon_concrete_note.pdf' },
      { url: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80', mediaType: 'image', fileName: 'green_building_concept.jpg' },
    ],
    createdAt: generateTimestamp(7, 2),
  },
  {
    id: 'mock-article-018',
    type: 'Article',
    title: 'Commissioning-ready documentation: what to collect from day one',
    summary: 'A practical structure for O&M files, as-built logs, and test records that avoids handover bottlenecks.',
    author: 'Raj Patel',
    field: 'Engineering',
    interests: ['commissioning', 'handover', 'article'],
    stats: `${getRandomEngagement().likes} likes • ${getRandomEngagement().comments} comments`,
    verified: true,
    media: [
      { url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', mediaType: 'document', fileName: 'commissioning_docs_framework.pdf' },
    ],
    createdAt: generateTimestamp(8, 3),
  },
];

export default mockCommunityData;
